# Generated by Django 4.1.5 on 2023-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('link', models.URLField(db_index=True, max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='thebox/%Y/%m/%d/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
