# Generated by Django 4.1.5 on 2023-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfront',
            name='description',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='aboutfront',
            name='link',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
