# Generated by Django 4.1.5 on 2023-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_alter_aboutfront_description_alter_aboutfront_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=280)),
                ('link', models.CharField(db_index=True, max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='thebox/%Y/%m/%d/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutFront',
        ),
    ]
