# Generated by Django 4.1.5 on 2023-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_aboutback_aboutpage_delete_aboutfront'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBack',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='available1',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='link',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
