# Generated by Django 4.1.5 on 2023-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_rename_aboutpage_aboutheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('link', models.CharField(db_index=True, max_length=128, null=True, unique=True)),
                ('image', models.ImageField(upload_to='thebox/%Y/%m/%d/')),
                ('available', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
