# Generated by Django 4.1.5 on 2023-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_aboutexprience_remove_aboutheader_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexprience',
            name='image',
            field=models.FileField(null=True, upload_to='thebox/%Y/%m/%d/'),
        ),
    ]
