# Generated by Django 4.1.5 on 2023-02-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0009_aboutexprience_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutexprience',
            name='image',
        ),
    ]
