# Generated by Django 4.1.5 on 2023-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0012_rename_images_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
