# Generated by Django 4.1.5 on 2023-03-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0014_alter_postimage_post_profesionalsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=15, null=True)),
                ('header', models.CharField(max_length=50, null=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CounterSelection', to='About.aboutexprience')),
            ],
        ),
    ]
