# Generated by Django 4.1.5 on 2023-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='thebox/%Y/%m/%d/')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=60)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
