# Generated by Django 4.1.5 on 2023-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link', models.URLField(db_index=True, max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='courses/%Y/%m/%d/')),
            ],
        ),
    ]
