# Generated by Django 4.1.5 on 2023-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navbar', '0002_navbarlogo_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link', models.URLField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='navbarlogo',
            name='image',
            field=models.ImageField(upload_to='thebox/%Y/%m/%d/'),
        ),
    ]
