# Generated by Django 4.1.5 on 2023-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navbar', '0003_navbarmenu_alter_navbarlogo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmenu',
            name='link',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
